

CREATE TABLE ORDER
(
    ID               BIGSERIAL      NOT NULL PRIMARY KEY,
    TITLE            VARCHAR(255)   NOT NULL,
    COST             DECIMAL(10, 2) NOT NULL,
    ORDER_DATE DATE           NOT NULL,
    DELIVERY VARCHAR(20)  NOT NULL DEFAULT 'PICKUP'

);
